apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor
  namespace: media
  labels:
    app: video-processor
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  minReadySeconds: 30
  selector:
    matchLabels:
      service: video-processor
  template:
    metadata:
      labels:
        app: video-processor
        service: video-processor
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      priorityClassName: media-highest-priority-linux
      #------------------------------------------------------
      # setting pod DNS policies to enable faster DNS resolution
      # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
      dnsConfig:
        options:
          # use FQDN everywhere 
          # any cluster local access from pods need full CNAME to resolve 
          # short names will not resolve to internal cluster domains
          - name: ndots
            value: "2"
          # dns resolver timeout and attempts
          - name: timeout
            value: "15"
          - name: attempts
            value: "3"
          # use TCP to resolve DNS instad of using UDP (UDP is lossy and pods need to wait for timeout for lost packets)
          - name: use-vc
          # open new socket for retrying
          - name: single-request-reopen
      #------------------------------------------------------
      volumes:
        # # `name` here must match the name
        # # specified in the volume mount
        # - name: demo-configmap-video-processor-volume
        #   configMap:
        #     # `name` here must match the name
        #     # specified in the ConfigMap's YAML
        #     name: demo-configmap
        - name: media-data-volume
          persistentVolumeClaim:
            claimName: media-azurefile-video-processor # PersistentVolumeClaim name in aks_manifests\prerequisites\k8s.yaml
      terminationGracePeriodSeconds: 300 # This must be set to a value that is greater than the preStop hook wait time.
      containers:
        - name: video-processor
          lifecycle:
            preStop:
              exec:
                command: ["sleep","180"]
          image: chdemosharedacr.azurecr.io/media/chmediaservice:1.1
          imagePullPolicy: Always
          volumeMounts:
            # - mountPath: /etc/config
            #   name: demo-configmap-video-processor-volume
            - mountPath: /media/data
              name: media-data-volume
          env:
            - name: MEDIA_PATH
              value: /media/data
          resources:
                limits:
                  memory: 4Gi # the memory limit equals to the request!
                  # no cpu limit! this is excluded on purpose
                requests:
                  memory: 4Gi
                  cpu: "2"