apiVersion: v1
kind: Namespace
metadata:
  name: media

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: media-system-highest-priority-linux
value: 10000000
globalDefault: true
description: "This priority class is used for highest priority media system services which are essential."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: media-highest-priority-linux
value: 1000000
globalDefault: false
description: "This priority class should be used for highest priority media service pods (linux) only."

# ---
# apiVersion: scheduling.k8s.io/v1
# kind: PriorityClass
# metadata:
#   name: media-medium-priority-linux
# value: 100000
# globalDefault: false
# description: "This priority class should be used for medium priority media service pods (linux) only. Will be default priority for pods with no priority class set."

# ---
# apiVersion: scheduling.k8s.io/v1
# kind: PriorityClass
# metadata:
#   name: media-lowest-priority-linux
# value: 10000
# globalDefault: false
# description: "This priority class should be used for lowest priority media service pods (linux) only."

# Resource quota allocation for each priority class
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: media-highest-priority-linux
  namespace: media
spec:
  hard:
    requests.cpu: "42"
    limits.memory: 100Gi
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["media-highest-priority-linux"]


# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: media-medium-priority-linux
#   namespace: media
# spec:
#   hard:
#     requests.cpu: "5"
#     limits.memory: 20Gi
#   scopeSelector:
#     matchExpressions:
#     - operator : In
#       scopeName: PriorityClass
#       values: ["media-medium-priority-linux"]

# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: media-lowest-priority-linux
#   namespace: media
# spec:
#   hard:
#     requests.cpu: "2"
#     limits.memory: 8Gi
#   scopeSelector:
#     matchExpressions:
#     - operator : In
#       scopeName: PriorityClass
#       values: ["media-lowest-priority-linux"]


# ---
# # HPA for dynamicstorage-videoprocessor
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: dynamicstorage-videoprocessor-hpa
#   namespace: media
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: dynamicstorage-videoprocessor
#   maxReplicas: 10
#   minReplicas: 1
#   behavior:
#     scaleDown:
#       stabilizationWindowSeconds: 120
#       policies:
#       - type: Percent
#         value: 50
#         periodSeconds: 60
#     scaleUp:
#       stabilizationWindowSeconds: 15
#       policies:
#       - type: Percent
#         value: 60
#         periodSeconds: 30
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 70